version: '3'
services:
  directus:
    container_name: jvds-directus9
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./database:/directus/database
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions/
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'sqlite3'
      DB_FILENAME: './database/data.db'

      ADMIN_EMAIL: 'robertwildling@gmail.com'
      ADMIN_PASSWORD: 'mRavel2023'
      
    depends_on:
      - cache

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: 'https://directus.example.com'

networks:
  directus: